name: Build and Test

on:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: apt install
      run: |
        sudo apt-get update & sudo apt-get install build-essential

    - name: run user's code
      run: |
        python3 main.py